default: &default
  adapter: mysql2
  encoding: utf8mb4
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: user
  password: password
  timeout: 5000

development:
  <<: *default
  database: example_development
  database: example_development

test:
  <<: *default
  database: example_test
  database: example_test

production:
  <<: *default
  database: example_production
  username: <%= ENV['EXAMPLE_DATABASE_USER'] %>
  password: <%= ENV['EXAMPLE_DATABASE_PASSWORD'] %>
